token: token             # Replace with a desired token
os:
  hostname: harv-test-node1        # Set a hostname. This can be omitted if DHCP server offers hostnames.
  password: root     # Replace with a your password
  ntp_servers:
    - ntp.aliyun.com
install:
  mode: create
  networks:
    harvester-mgmt:       # The management bond name. This is mandatory.
      interfaces:
      - name: ens33
      default_route: true
      method: dhcp
      bond_options:
        mode: balance-tlb
        miimon: 100
  device: /dev/sda
  iso_url: http://192.168.5.79/harvester-pxe/artifacts/v1.0.2/harvester-amd64.iso
  vip: 192.168.5.81       # The VIP to access the Harvester GUI. Make sure the IP is free to use.
  vip_mode: static        # Or dhcp, check configuration file for more information.
