server_url: https://192.168.5.81:6443
token: token             # Replace with a desired token
os:
  hostname: harv-test-node2
  password: root     # Replace with a your password
  ntp_servers:
    - ntp.aliyun.com
install:
  mode: join
  networks:
    harvester-mgmt:       # The management bond name. This is mandatory.
      interfaces:
      - name: ens33
      default_route: true
      method: dhcp
      bond_options:
        mode: balance-tlb
        miimon: 100
  device: /dev/sda
  iso_url: http://192.168.5.79/harvester-pxe/artifacts/v1.0.0/harvester-amd64.iso
